config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  post 'productos/formulario_kit', as: 'formulario_kit'
  post 'productos/agregar_producto_kit', as: 'agregar_producto_kit'
  get 'welcome/index'
  resources :categorias
  resources :productos
  resources :unidades
  resources :configuraciones
  resources :empresas
  resources :cambio_sucursal
  resources :proveedores
  resources :clientes
  resources :tipos_pagos
  resources :inventarios
  resources :sucursales
  resources :terminales
  resources :cajas_registradoras
  resources :descuentos
  resources :cambio_sucursal do
    post :cambiar, :on => :collection
  end
  resources :empleados
  get 'permisos/mod_usuarios'
  get 'permisos/show_modulos'
  get 'permisos/mod_usuarios_rest'
  post 'terminales/actualiza'
  post 'terminales/caja_registradora'
  post 'permisos/guardar_cambios'
  post 'empleados/actualiza'
  post 'descuentos/opciones'
  post 'descuentos/agregar_producto'
  post 'descuentos/agregar_productos'
  post 'descuentos/obtener_categoria'
  post 'descuentos/total_producto'

  root 'welcome#index'

end

app/models/cajas_registradora.rb
class CajasRegistradora < ActiveRecord::Base
  has_many :terminales
end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  has_and_belongs_to_many :productos
  has_many :descuentos
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/models/descuento.rb
class Descuento < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :terminal
  belongs_to :categoria
  has_many :descuentos_productos
  has_many :descuentos_productos, dependent: :destroy
  has_many :productos, through: :descuentos_productos
end

app/models/descuentos_producto.rb
class DescuentosProducto < ActiveRecord::Base
  belongs_to :descuento
  belongs_to :producto
end

app/models/empleado.rb
class Empleado < ActiveRecord::Base
	has_many :usuarios, dependent: :destroy
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base

   has_attached_file :imagen, styles: { medium: "200x200>", thumb: "200x200>" }, default_url: "/images/:style/missing.png", validate_media_type: false

validates_attachment_content_type :imagen, content_type: /\Aimage\/.*\Z/

end

app/models/inventario.rb
class Inventario < ActiveRecord::Base
  has_many :terminales
end

app/models/kit.rb
class Kit < ActiveRecord::Base
end

app/models/modulo.rb
class Modulo < ActiveRecord::Base
	has_many :usuarios, through: :modulos_usuarios
end

app/models/modulos_usuario.rb
class ModulosUsuario < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :modulo
end

app/models/producto.rb
class Producto < ActiveRecord::Base
  belongs_to :unidad
  has_and_belongs_to_many :categorias
  has_many :descuentos_productos
  has_many :descuentos, through: :descuentos_productos
  has_attached_file :imagen, styles: { medium: "200x200>", thumb: "200x200>" }, default_url: "/images/:style/missing.png", validate_media_type: false
  validates_attachment_content_type :imagen, content_type: /\Aimage\/.*\Z/
end

app/models/proveedor.rb
class Proveedor < ActiveRecord::Base
end

app/models/rol.rb
class Rol < ActiveRecord::Base
	belongs_to :usuario
end

app/models/sucursal.rb
class Sucursal < ActiveRecord::Base
  has_many :terminales
end

app/models/terminal.rb
class Terminal < ActiveRecord::Base
  belongs_to :sucursal
  belongs_to :cajas_registradora
  belongs_to :inventario

  #validates :nombre, uniqueness: { case_sensitive: false }
end

app/models/tipos_pago.rb
class TiposPago < ActiveRecord::Base
end

app/models/unidad.rb
class Unidad < ActiveRecord::Base
  belongs_to  :producto
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  #devise :database_authenticatable, :registerable,
   #      :recoverable, :rememberable, :validatable
  belongs_to :empleado
  belongs_to :rol
  has_many :modulos_usuarios, dependent: :destroy
  has_many :modulos, through: :modulos_usuarios
  
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_clientes, except: [:index, :new, :create]
  before_action :definirControlador, :quitarBandera

  def definirControlador
    @controlador = 'clientes'
    @controladorSingular = 'el cliente'
  end

  def quitarBandera
    @creacion = false
  end

  def index
    @clientes = Cliente.all.order :nombre
  end

  def show
    @clientes = Cliente.find(params[:id])
  end
  def new
    @clientes = Cliente.new
    @creacion = true
  end

  def edit
    @clientes = Cliente.find(params[:id])

    @estado = @clientes.estado
  end

  def create
    @clientes = Cliente.new(cliente_params)
    if Cliente.find_by(nombre: params[:cliente][:nombre]).blank?
      if @clientes.save
        flash[:success] = "Cliente creado exitosamente"
        redirect_to @clientes
      else
        flash[:error] = "Error al crear cliente"
        render :new
      end
    else
      @creacion = true
      flash[:info] = 'El cliente: ' + params[:cliente][:nombre] + ' ya está registrado en el sistema'
      render :new
    end
  end

  def update
    if Cliente.where('id != ? and nombre = ?', params[:id], params[:cliente][:nombre]).present?
      @clientes = Cliente.find(params[:id])
      @estado = @clientes.estado
      flash[:info] = 'El cliente: ' + params[:cliente][:nombre] + ' ya está registrado en el sistema'
      render :edit
    else
      if @clientes.update(cliente_params)
        flash[:success] = "Cliente actualizado exitosamente"
        redirect_to clientes_path
      else
        flash[:error] = "Error al actualizar cliente"
        render :edit
      end
    end
  end

  def destroy
    if@clientes.destroy
      flash[:success] = "Cliente Eliminado exitosamente"
      redirect_to clientes_path
    else
      flash[:error]= "Error al eliminar cliente"
    end

  end

  private

  def cliente_params
    params.require(:cliente).permit(:nombre,:rfc, :email, :telefono, :direccion, :ciudad, :estado, :codigo_Postal)
  end

  def set_clientes
    @clientes = Cliente.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :usuario
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:usuario]
  end

end

app/views/clientes/_form.html.erb
<%= form_for(@clientes) do |f| %>
  <table class="table table-hover">
    <fieldset>
      <% @clientes.errors.full_messages.each do |error_message| %>
        <%=  error_message %>
      <% end %>
      <tr>
        <td><b><%= f.label :nombre, 'Nombre*' %></b> <br><small class="form-text text-muted">Nombre que identifica al
          cliente</small></td>
        <td><%= f.text_field :nombre, placeholder: 'Ingresar nombre del cliente',class: 'form-control',id: 'nombreC',
                             type: 'text', onkeypress: 'return validarNombre(event);', maxlength: 60%><small id="msg_nombreC"></small></td>

      </tr>
      <tr>
        <td><b><%= f.label :rfc, 'RFC' %></b><br><small class="form-text text-muted">Registro Federal de Contribuyentes
          <br>que identifica al cliente como único</small></td>
        <td><br><%= f.text_field :rfc, placeholder: 'Ingresar RFC', class: 'form-control',maxlength: 13,
                                 type: 'text', id: 'rfc'%><small id="rfcmensaje"></small> </td>
      </tr>
      <tr>
        <td><b><%= f.label :email, 'Correo Electrónico'%></b><br><small  class="form-text text-muted">Correo Electrónico
          propio del cliente <br>para su futura comunicación</small></td>
        <td><br><%= f.text_field :email, placeholder: 'Ingresar correo electrónico', class: 'form-control',id: 'email1'%><small id="msemail"></small></td>
      </tr>
      <tr>
        <td><b><%= f.label :telefono, 'Teléfono' %></b><br><small class="form-text text-muted">Registro del Teléfono del
          cliente para <br> su futura comunicación</small></td>
        <td><br><%= f.text_field :telefono, placeholder: 'Ingresar el teléfono', class: 'form-control',
                                 onkeypress: 'return validarTelefono(event)',type: 'text'%> </td>
      </tr>
      <tr>
        <td><b><%= f.label :direccion, 'Dirección' %></b><small class="form-text text-muted">Ubicación fiscal de la
          sucursal</small> </td>
        <td><%= f.text_field :direccion, placeholder: 'Ingresar dirección',class: 'form-control'%></td>
      </tr>
      <tr>
        <td><b><%= f.label :ciudad, 'Ciudad' %></b><small class="form-text text-muted">Municipio donde se ubica</small></td>
        <td><%= f.text_field :ciudad, placeholder: 'Ingresar Ciudad', class: 'form-control',type: 'text'%></td>
      </tr>
      <tr>
        <td><b><%= f.label :estado, 'Estado '%></b><small class="form-text text-muted">Entidad federativa</small></td>
        <td><br><%= f.select :estado, @estados, {:select =>@estado },{class: 'custom-select'}%></td>
      </tr>
      <tr>
        <td><b><%= f.label :codigo_Postal,'Código Postal' %></b></td>
        <td><%= f.text_field :codigo_Postal, placeholder: 'Ingresar código postal',class: 'form-control',
                             onkeypress: 'return validar_cp(event)',type: 'text'%></td>
      </tr>
    </fieldset>
  </table>
  <table class="table table-responsive-sm">
    <tr>
      <td align="center">
        <!--botón nombre, cambia respecto a la acción de deba hacer crear o modificar-->
        <br>
        <small class="form-text text-muted">Nota: Los campos marcados con * son obligatorios</small>
        <br>
        <!-- funcion cancelar-->
        <% if nombre=="Crear Cliente" %>
          <%= f.submit 'Guardar', class: 'btn btn-primary btn-sm', onclick: 'return validarFormularioCliente();',id:'btnGuardar'%>
        <% else %>
          <%= f.submit 'Guardar Cambios', class: 'btn btn-primary btn-sm', onclick: 'return validarFormularioCliente();',id:'btnGuardar'%>
        <% end %>
        <%= link_to 'Cancelar', '#', class: 'btn btn-danger btn-sm', data: {toggle: 'modal', target: '#ModalForm'} %>
      </td>
    </tr>
  </table>
<% end %>

app/views/clientes/edit.html.erb
<h4 class="text-center">Modificación del Cliente</h4><br>
<%= render 'form', nombre: 'Editar Cliente' %>

app/views/clientes/index.html.erb
    <h4 class="text-center">Catálogo de Clientes</h4><br>
    <% if @clientes.size >0 %>
      <table class="table table-sm table-bordered">
        <thead class="bg-primary text-light">
        <tr>
          <th>Nombre</th>
          <th>RFC</th>
          <th>Teléfono(s)</th>
          <th colspan="3" class="text-center" width="15%">Opciones</th>
        </tr>
        </thead>
        <tbody>
        <%@clientes.each do |cliente| %>
          <tr>
              <td> <%= cliente.nombre %></td>
              <td> <%= cliente.rfc %></td>
              <td><%= cliente.telefono %></td>
              <td align="center"><%= link_to cliente, title: 'Mostrar' do %>
                  <%= fa_icon "eye" %>
                <% end %></td>
              <td align="center"><%= link_to edit_cliente_path(cliente),title: 'Modificar' do %>
                  <%= fa_icon "edit" %>
                <% end %></td>
              <td align="center">
                <%= link_to (fa_icon 'trash'), '#',title: 'Eliminar', data: { toggle: 'modal', target: '#ModalIndex' },
                            onclick:('cambiarIdYNombre('+cliente.id.to_s+',"'+@controlador.to_s+'","'+ @controladorSingular.to_s+'","'+ cliente.nombre+'");return false;') %></td>

          </tr>
        <% end %>
        </tbody>
      </table>
    <% else %>
      <br>
      <h5 align="center"><%= "No existe cliente actualmente" %> </h5>
    <% end %>
    <br/>
    <table class="table">
      <tr>
        <td align="center"><%= link_to 'Nuevo', new_cliente_path, class: 'btn btn-primary btn-sm' %></td>
      </tr>
    </table>

app/views/clientes/new.html.erb
<h4 class="text-center">Nuevo Cliente</h4><br>
<%= render 'form', nombre: 'Crear Cliente' %>

app/views/clientes/show.html.erb
<article>
  <h4 align="center"> Vista del Cliente </h4>
  <table class="table ">

    <tr>
      <td width="30%"><b> Nombre</b> <br><small>Nombre que identifica al cliente</small></td>
      <td colspan="3"> <%= @clientes.nombre %></td>
    </tr>
    <tr>
      <td ><b> Correo Electrónico</b> <br><small >Correo Electrónico propio
        del cliente <br>para su futura comunicación</small> </td>
      <td colspan="3"> <%= @clientes.email %></td>
    </tr>
    <tr>
      <td ><b> RFC</b> <br><small>Registro Federal de Contribuyentes<br>del cliente</small></td>
      <td colspan="3"> <%= @clientes.rfc %></td>
    </tr>
    <tr>
      <td ><b> Teléfono(s)</b><br> <small>Registro del Teléfono del cliente
        <br> para su futura comunicación</small></td>
      <td colspan="3"> <%= @clientes.telefono %></td>
    </tr>
    <tr>
      <td width="50"><b>Dirección</b><br><small>Ubicación fiscal de la sucursal</small></td>
      <td width="50"> <%= @clientes.direccion %></td>
      <td ><b> Código Postal </b></td>
      <td > <%= @clientes.codigo_Postal %></td>
    </tr>
    <tr>
      <td ><b> Ciudad</b><br><small>Municipio donde se ubica</small></td>
      <td > <%= @clientes.ciudad %></td>
      <td ><b>Estado</b><br><small>Entidad federativa</small> </td>
      <td > <%= @clientes.estado %></td>
    </tr>

    <br>
  </table>
  <br/>
  <table class="table table-responsive-sm">
    <tr>
      <td align="center">
        <%= link_to 'Modificar', edit_cliente_path(@clientes), class: 'btn btn-primary btn-sm'%>
      <%= link_to 'Nuevo', new_cliente_path, class: 'btn btn-primary btn-sm' %>
        <%= link_to 'Regresar', clientes_path, class: 'btn btn-primary btn-sm'%>
      </td>
    </tr>
  </table>
</article>

app/views/clientes/ventas.html.erb
<h1><%= "Historial de Compras" %></h1>
<br/>
<table class="titledlist" width="100%">
  <thead>
  <tr>
    <th><b><%=  "Folio" %></b></th>
    <th><b><%=  "Fecha" %></b></th>
    <th><b><%=  "Vendedor" %></b></th>
    <th><b><%=  "Lugar" %> </b></th>
    <th><b><%=  "Total" %> </b></th>
    <th><b><%=  "Detalle" %> </b></th>
  </tr>
  </thead>
</table>
<br/>
<%= link_to 'Regresar', clientes_path, class: 'btn btn-primary btn-sm'%>