config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  post 'productos/formulario_kit', as: 'formulario_kit'
  post 'productos/agregar_producto_kit', as: 'agregar_producto_kit'
  get 'welcome/index'
  resources :categorias
  resources :productos
  resources :unidades
  resources :configuraciones
  resources :empresas
  resources :cambio_sucursal
  resources :proveedores
  resources :clientes
  resources :tipos_pagos
  resources :inventarios
  resources :sucursales
  resources :terminales
  resources :cajas_registradoras
  resources :descuentos
  resources :cambio_sucursal do
    post :cambiar, :on => :collection
  end
  resources :empleados
  get 'permisos/mod_usuarios'
  get 'permisos/show_modulos'
  get 'permisos/mod_usuarios_rest'
  post 'terminales/actualiza'
  post 'terminales/caja_registradora'
  post 'permisos/guardar_cambios'
  post 'empleados/actualiza'
  post 'descuentos/opciones'
  post 'descuentos/agregar_producto'
  post 'descuentos/agregar_productos'
  post 'descuentos/obtener_categoria'
  post 'descuentos/total_producto'

  root 'welcome#index'

end

app/models/cajas_registradora.rb
class CajasRegistradora < ActiveRecord::Base
  has_many :terminales
end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  has_and_belongs_to_many :productos
  has_many :descuentos
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/models/descuento.rb
class Descuento < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :terminal
  belongs_to :categoria
  has_many :descuentos_productos
  has_many :descuentos_productos, dependent: :destroy
  has_many :productos, through: :descuentos_productos
end

app/models/empleado.rb
class Empleado < ActiveRecord::Base
	has_many :usuarios, dependent: :destroy
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base

   has_attached_file :imagen, styles: { medium: "200x200>", thumb: "200x200>" }, default_url: "/images/:style/missing.png", validate_media_type: false

validates_attachment_content_type :imagen, content_type: /\Aimage\/.*\Z/

end

app/models/inventario.rb
class Inventario < ActiveRecord::Base
  has_many :terminales
end

app/models/kit.rb
class Kit < ActiveRecord::Base
end

app/models/modulo.rb
class Modulo < ActiveRecord::Base
	has_many :usuarios, through: :modulos_usuarios
end

app/models/modulos_usuario.rb
class ModulosUsuario < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :modulo
end

app/models/producto.rb
class Producto < ActiveRecord::Base
  belongs_to :unidad
  has_and_belongs_to_many :categorias
  has_many :descuentos_productos
  has_many :descuentos, through: :descuentos_productos
  has_attached_file :imagen, styles: { medium: "200x200>", thumb: "200x200>" }, default_url: "/images/:style/missing.png", validate_media_type: false
  validates_attachment_content_type :imagen, content_type: /\Aimage\/.*\Z/
end

app/models/proveedor.rb
class Proveedor < ActiveRecord::Base
end

app/models/rol.rb
class Rol < ActiveRecord::Base
	belongs_to :usuario
end

app/models/sucursal.rb
class Sucursal < ActiveRecord::Base
  has_many :terminales
end

app/models/terminal.rb
class Terminal < ActiveRecord::Base
  belongs_to :sucursal
  belongs_to :cajas_registradora
  belongs_to :inventario

  #validates :nombre, uniqueness: { case_sensitive: false }
end

app/models/tipos_pago.rb
class TiposPago < ActiveRecord::Base
end

app/models/unidad.rb
class Unidad < ActiveRecord::Base
  belongs_to  :producto
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  #devise :database_authenticatable, :registerable,
   #      :recoverable, :rememberable, :validatable
  belongs_to :empleado
  belongs_to :rol
  has_many :modulos_usuarios, dependent: :destroy
  has_many :modulos, through: :modulos_usuarios
  
end

app/controllers/cambio_sucursal_controller.rb
class CambioSucursalController < ApplicationController

 #before_action :set_impuesto, except: [:index, :new, :create]


  def index
    @terminales = Terminal.all
    @terminales_ = []
    for t in @terminales
      @terminales_ << {:id => t.id, :sucursal => t.sucursal.nombre}
    end
    @terminales_ = @terminales_.sort_by { |i| i[:sucursal] }
    @terminales_ids = @terminales_.map{ |i| i[:id] }
    @terminales = []
    for t in @terminales_ids
      @terminales << (Terminal.find t)
    end
  end

  def cambiar
      cookies.permanent["TerminalActual"] = params[:id_ter]
      redirect_to cambio_sucursal_path(params[:id_ter])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :usuario
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:usuario]
  end

end

app/views/cambio_sucursal/index.html.erb
<!-- Vista del usuario para escoger una sucursal para cambiar-->
<h3 align="center">Cambio de Sucursal y Terminal</h3>
<br/>
<% if @terminales.size > 0 %>
  <% if cookies["TerminalActual"].nil? %>
    <table class="table table-sm text-center ">
      <tr>
        <td><h4>Es necesario registrar su Terminal para poder utilizar las funcionalidades del sistema</h4></td>
      </tr>
      <tr>
        <td><h5>Seleccione Sucursal y Terminal a asignar</h5></td>
      </tr>
    </table>
  <% else %>
    <h3 align="center">Elija la Sucursal - Terminal a la que se desea cambiar</h3>
  <% end %>
  <%=form_tag action: :cambiar do |f| %>
    <table class="table text-center">
      <tr>
        <td><%= "Sucursal - Terminal: " %><%= select_tag 'id_ter', options_for_select(@terminales.collect {|p| [p.sucursal.nombre + " - " + p.nombre, p.id]},cookies["TerminalActual"]) %></td>
      </tr>
    </table><br/>
    <table class="table text-center">
      <tr>
        <td>
          <%= submit_tag "Confirmar Cambio" , class: 'btn btn-primary'%>
          <%= link_to 'Regresar', configuraciones_path, class: 'btn btn-primary'%>
        </td>
      </tr>
    </table>
  <%end %><br><br>
<%else %>
  <h4>No existen terminales registradas en el sistema<br/>Consulte al Administrador</h4><br/>
  <%= link_to 'Crear terminal nuevo', terminales_path, class: 'btn btn-primary btn-sm' %>
<%end %>

app/views/cambio_sucursal/show.html.erb
<!-- Leyenda que se mostrará durante la creación de la cookie y la realización del cambio de sucursal-->
<table class="table table-hover text-center">
  <tr>
    <td><h1><%= 'titulo de sucursal' %></h1></td>
  </tr>
  <tr>
    <td><h3>Cambiando su Sucursal y Terminal ........</h3></td>
  </tr>
</table>

<!-- script que direccionará al principal de la aplicación-->
<script type="text/javascript">
    window.location = "/"
</script>