config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  post 'productos/formulario_kit', as: 'formulario_kit'
  post 'productos/agregar_producto_kit', as: 'agregar_producto_kit'
  get 'welcome/index'
  resources :categorias
  resources :productos
  resources :unidades
  resources :configuraciones
  resources :empresas
  resources :cambio_sucursal
  resources :proveedores
  resources :clientes
  resources :tipos_pagos
  resources :inventarios
  resources :sucursales
  resources :terminales
  resources :cajas_registradoras
  resources :descuentos
  resources :cambio_sucursal do
    post :cambiar, :on => :collection
  end
  resources :empleados
  get 'permisos/mod_usuarios'
  get 'permisos/show_modulos'
  get 'permisos/mod_usuarios_rest'
  post 'terminales/actualiza'
  post 'terminales/caja_registradora'
  post 'permisos/guardar_cambios'
  post 'empleados/actualiza'
  post 'descuentos/opciones'
  post 'descuentos/agregar_producto'
  post 'descuentos/agregar_productos'
  post 'descuentos/obtener_categoria'
  post 'descuentos/total_producto'

  root 'welcome#index'

end

app/models/cajas_registradora.rb
class CajasRegistradora < ActiveRecord::Base
  has_many :terminales
end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  has_and_belongs_to_many :productos
  has_many :descuentos
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/models/descuento.rb
class Descuento < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :terminal
  belongs_to :categoria
  has_many :descuentos_productos
  has_many :descuentos_productos, dependent: :destroy
  has_many :productos, through: :descuentos_productos
end

app/models/descuentos_producto.rb
class DescuentosProducto < ActiveRecord::Base
  belongs_to :descuento
  belongs_to :producto
end

app/models/empleado.rb
class Empleado < ActiveRecord::Base
	has_many :usuarios, dependent: :destroy
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base

   has_attached_file :imagen, styles: { medium: "200x200>", thumb: "200x200>" }, default_url: "/images/:style/missing.png", validate_media_type: false

validates_attachment_content_type :imagen, content_type: /\Aimage\/.*\Z/

end

app/models/inventario.rb
class Inventario < ActiveRecord::Base
  has_many :terminales
end

app/models/kit.rb
class Kit < ActiveRecord::Base
end

app/models/modulo.rb
class Modulo < ActiveRecord::Base
	has_many :usuarios, through: :modulos_usuarios
end

app/models/modulos_usuario.rb
class ModulosUsuario < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :modulo
end

app/models/producto.rb
class Producto < ActiveRecord::Base
  belongs_to :unidad
  has_and_belongs_to_many :categorias
  has_many :descuentos_productos
  has_many :descuentos, through: :descuentos_productos
  has_attached_file :imagen, styles: { medium: "200x200>", thumb: "200x200>" }, default_url: "/images/:style/missing.png", validate_media_type: false
  validates_attachment_content_type :imagen, content_type: /\Aimage\/.*\Z/
end

app/models/proveedor.rb
class Proveedor < ActiveRecord::Base
end

app/models/rol.rb
class Rol < ActiveRecord::Base
	belongs_to :usuario
end

app/models/sucursal.rb
class Sucursal < ActiveRecord::Base
  has_many :terminales
end

app/models/terminal.rb
class Terminal < ActiveRecord::Base
  belongs_to :sucursal
  belongs_to :cajas_registradora
  belongs_to :inventario

  #validates :nombre, uniqueness: { case_sensitive: false }
end

app/models/tipos_pago.rb
class TiposPago < ActiveRecord::Base
end

app/models/unidad.rb
class Unidad < ActiveRecord::Base
  belongs_to  :producto
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  #devise :database_authenticatable, :registerable,
   #      :recoverable, :rememberable, :validatable
  belongs_to :empleado
  belongs_to :rol
  has_many :modulos_usuarios, dependent: :destroy
  has_many :modulos, through: :modulos_usuarios
  
end

app/controllers/empleados_controller.rb
class EmpleadosController < ApplicationController
	
	before_action :set_empleado, only: [:show, :edit, :update, :destroy]
	before_action :definirControlador, :quitarBandera

	def index
		@empleados = Empleado.all
	end

	def show
	end

	def new
		@empleado = Empleado.new 
		@usuario = Usuario.new
		@roles = Rol.all
		@creacion = true

		@rol = 1
	end

	def edit
		@roles = Rol.all
		@usuario = Usuario.find_by(empleado_id: params[:id])
		@rol = @usuario.rol_id
		@estado = @usuario.empleado.estado
	end

	def create
		@empleado = Empleado.new(empleado_params)
		if Usuario.find_by(usuario: params[:usuario][:usuario]).blank?
			@usuario = @empleado.usuarios.new(usuario_params)
			begin
				Empleado.transaction do
					@empleado.save
					Usuario.transaction do
						@usuario.save
          #  @user.save
						flash[:success] = 'El Usuario-Empleado ha sido creado satisfactoriamente'
						redirect_to @empleado
					end
				end
			rescue
				#message
			end
		else
			@roles = Rol.all
			@creacion = true
			@rol = params[:usuario][:rol_id].to_i
			@usuario = Usuario.new(usuario_params)
			flash[:info] = 'El usuario: ' + @usuario.usuario + ' ya está registrado en el sistema'
			render :new
		end
	end

	def actualiza
		@empleado = Empleado.find(params[:id])
		@usuario = Usuario.find_by(empleado_id: @empleado.id)
		if Usuario.where('id != ? and usuario = ?', @usuario.id, params[:usuario][:usuario]).present?
			@roles = Rol.all
			@rol = params[:usuario][:rol_id].to_i
	    	flash[:info] = 'El usuario: ' + params[:usuario][:usuario] + ' ya está registrado en el sistema'
	    	render :edit
		else
			begin
				Empleado.transaction do
					@empleado.update(empleado_params)
					Usuario.transaction do
						@usuario.update(usuario_params)
						@user = @usuario
						flash[:success] = "El Empleado ha sido actualizado satisfactoriamente"
						redirect_to @empleado
					end
				end
			rescue
				#message
			end
		end
	end

	def destroy
	    @empleado.destroy
	    flash[:success] = "El Empleado ha sido eliminado satisfactoriamente"
	    redirect_to empleados_url
	end

	def definirControlador
		@controlador = 'empleados'
		@controladorSingular = 'el empleado'
	end

	def quitarBandera
		@creacion = false
	end

	private
	
	def set_empleado
		@empleado = Empleado.find(params[:id])
	end

	def empleado_params
		params.require(:empleado).permit(:nombre_completo, :apellido_paterno, :apellido_materno, :rfc, 
			:fecha_nacimiento, :fecha_registro, :direccion, :ciudad, :estado, :codigo_postal)
	end

	def usuario_params
		params.require(:usuario).permit(:rol_id, :usuario, :email,:tipo, :contrasena_cifrado)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :usuario
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:usuario]
  end

end

app/views/empleados/_formempleado.erb
<h5 class="text-center">Datos del empleado</h5><br/>
<table class="table table-sm">
	<tr>
		<td width="35%"><label>Nombre*</label><br/><small>Nombre del empleado</small></td>
			<td><%= text_field :empleado, :nombre_completo, class: 'form-control', autofocus: true, maxlength: 20%>
			<small id="nombre"></small></td>
		</tr>
		<tr>
			<td width="35%"><label>Apellido paterno*</label><br/><small>Apellido paterno del empleado</small></td>
			<td><%= text_field :empleado, :apellido_paterno, class: 'form-control', maxlength: 20%>
			<small id="app_p"></small></td>
		</tr>
		<tr>
			<td width="35%"><label>Apellido materno*</label><br/><small>Apellido materno del empleado</small></td>
			<td><%= text_field :empleado, :apellido_materno, class: 'form-control', maxlength: 20%>
			<small id="app_m"></small></td>
		</tr>
		<tr>
			<td width="35%"><label>RFC*</label><br/><small>Registro Federal de Contribuyentes del empleado</small></td>
			<td><%= text_field :empleado, :rfc, class: 'form-control mayuscula', maxlength: 13, onkeyup:"mayuscula(this)"%>
			<small id="rfc"></small></td>
		</tr>
		<tr>
			<td width="35%"><label>Fecha de nacimiento*</label><br/><small>Fecha de nacimiento del empleado</small></td>
			<td>
				<div class="input-group">
					<%= text_field :empleado, :fecha_nacimiento, class: 'form-control', id: 'fecha_nacimiento', readonly: true%>
					<div class="input-group-append">
						<div class="input-group-text">
							<%= fa_icon 'calendar', class: 'cursor text-danger' %>
						</div>
					</div>
				</div>
				<small id="fecha_n"></small>
			</td>
		</tr>
		<tr>
			<td width="35%"><label>Fecha de registro*</label><br><small>Fecha de registro del empleado al sistema</small></td>
			<td>
				<div class="input-group">
					<%= text_field :empleado, :fecha_registro, class: 'form-control', id: 'fecha_registro', readonly: true%>
					<div class="input-group-append">
						<span class="input-group-text">
							<%= fa_icon 'calendar', class: 'cursor text-danger' %>
						</span>
					</div>
				</div>
				<small id="fecha_r"></small>
			</td>
		</tr>
		<tr>
			<td width="35%"><label>Dirección</label><br/><small>Ubicación fiscal de la sucursal</small></td>
			<td><%= text_field :empleado, :direccion, class: 'form-control mayuscula', maxlength: 60%></td>
		</tr>
		<tr>
			<td width="35%"><label>Ciudad</label><br/><small>Municipio donde se ubica</small></td>
			<td><%= text_field :empleado, :ciudad, class: 'form-control mayuscula', maxlength: 50%></td>
		</tr>
		<tr>
			<td width="35%"><label>Estado</label><br/><small>Entidad federativa</small></td>
			<td><%= select :empleado, :estado, @estados, {select: @estados},{class: 'custom-select'}%></td>
		</tr>
		<tr>
			<td width="35%"><label>Código postal</label></td>
			<td><%= text_field :empleado, :codigo_postal, class: 'form-control', onkeypress: 'return validar_cp(event)', maxlength: 8%></td>
		</tr>		
</table>

app/views/empleados/_formusuario.erb
<h5 class="text-center">Datos del usuario</h5><br/>
<table  class="table table-sm">
	<tr>
		<td width="40%"><label>Nombre de usuario*</label></br><small>Nombre único que identifica al usuario</small></td>
		<td><%= text_field :usuario, :usuario, class: 'form-control', maxlength: 20, onkeypress: 'return validarUsuario(event, this)'%>
			<small id="usuario"></small></td>
	</tr>
	<tr>
		<td width="40%"><label>Email*</label></br><small>Dirección de correo electrónico</small></td>
		<td><%= text_field :usuario, :email, class: 'form-control', maxlength: 35%>
			<small id="email"></small></td>
	</tr>
	<tr>
		<td width="40%"><label>Rol</label></br><small>Nivel de privilegios del usuario</small></td>
		<td>

       <%= select :usuario, :tipo, @tipos, {select: @tipos}, class:'form-control'%>

		</td>
	</tr>
	<tr>
		<td width="40%"><label>Contraseña*</label><br/><small>Palabra secreta para la restricción de acceso al sistema</small></td>
		<td><%= text_field :usuario, :contrasena_cifrado, class: 'form-control', type:'password', maxlength: 45%>
			<small id="pass"></small></td>
	</tr>
	<tr>
		<td><label>Confirmar contraseña*</label><br/><small>Se debe confirmar la contraseña de acceso al sistema</small></td>
		<td><%= text_field :usuario, :contrasena_cifrado, class: 'form-control', type: 'password', maxlength: 45, id: 'user_confirmar_contrasena' %>
			<small id="pass_confirm"></small>
		</td>
	</tr>
</table>

app/views/empleados/edit.html.erb
<h4 class="text-center">Modificación del Empleado-Usuario</h4>
<br/>

<%= form_tag :action => :actualiza, :id => @empleado.id do %>
	<div class="row">
		<div class="col-md-6">
			<%= render 'formempleado' %>
		</div>
		<div class="col-md-6">
			<%= render 'formusuario' %>
		</div>
	</div>
	<div class="text-center">
		<small>Nota: Los campos marcados con * son obligatorios</small><br/><br/>
		<%= submit_tag "Guardar cambios", :onclick=>"return validarFormularioEmpleados()", class: 'btn btn-sm btn-primary', id: 'btnGuardar'%>
        <%= link_to "Cancelar", '#', class: 'btn btn-sm btn-danger', data: { toggle: 'modal', target: '#ModalForm'} %>
	</div><br/><br/>
<% end %>

app/views/empleados/index.html.erb
<h4 class="text-center">Catálogo de Empleados</h4><br/>
<% if @empleados.size > 0 %>
	<table class="table table-bordered table-sm table-hover">
		<thead class="bg-primary text-white">
			<tr>
				<th>Nombre</th>
				<th>Ap. Paterno</th>		
				<th>Ap. Materno</th>
				<th>Registro</th>
				<th colspan="3" class="text-center">Opciones</th>
			</tr>
		</thead>
		<tbody>
			<% @empleados.each do |empleado| %>
				<tr>
					<td><%= empleado.nombre_completo %></td>
					<td><%= empleado.apellido_paterno %></td>
					<td><%= empleado.apellido_materno %></td>
					<td><%= empleado.fecha_registro %></td>
					<td class="text-center"><%= link_to empleado do %>
							<%= fa_icon 'eye', title: 'Mostrar' %>
						<% end %>
					</td>
					<td class="text-center"><%= link_to edit_empleado_path(empleado) do %>
							<%= fa_icon 'edit', title: 'Modificar' %>
						<% end %>
					</td>
			        <td class="text-center">
			               <%= link_to (fa_icon 'trash'), '#', data: { toggle: 'modal', target: '#ModalIndex' } ,
		                            onclick:('cambiarIdYNombre('+empleado.id.to_s+',"'+@controlador.to_s+'","'+ @controladorSingular.to_s+'","'+ (empleado.nombre_completo + ' ' + empleado.apellido_paterno + ' ' + empleado.apellido_materno)+'");return false;'),
		                            title: 'Eliminar'
		                	%>
			        </td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% else %>
	<h5 class="text-center">No existen Empleados actualmente</h5>
<% end %>
<table class="table text-center">
	<tr>
		<td><%= link_to 'Nuevo', new_empleado_path, class: 'btn btn-sm btn-primary' %></td>
	</tr>
</table>
  

app/views/empleados/new.html.erb
<h4 class="text-center">Nuevo Empleado - Usuario</h4>
<br/>
<%= form_tag :action=>:create do %>
	<div class="row">
		<div class="col-md-6">
			<%= render 'formempleado' %>
		</div>
		<div class="col-md-6">
			<%= render 'formusuario' %>
		</div>
	</div>
	<div class="text-center">
		<small>Nota: Los campos marcados con * son obligatorios</small><br/><br/>
		<%= submit_tag "Guardar", :onclick=>"return validarFormularioEmpleados()", class: 'btn btn-sm btn-primary', id: 'btnGuardar'%>
        <%= link_to "Cancelar", '#', class: 'btn btn-sm btn-danger', data: { toggle: 'modal', target: '#ModalForm'} %>
	</div><br/><br/>
<% end %>

app/views/empleados/show.html.erb
<h4 class="text-center">Vista de Empleado-Usuario</h4>
  	</br>
	<div class="row">
		<div class="col-md-7">
			<h5 class="text-center">Datos del Empleado</h5>
			</br>
			<table class="table table-sm table_show">
				<tr>
					<td><b>Nombre</b><br/><small>Nombre del empleado</small></td>
					<td><%= @empleado.nombre_completo %></td>
				</tr>
				<tr>
					<td><b>Apellido paterno</b><br/><small>Apellido paterno del empleado</small></td>
					<td><%= @empleado.apellido_paterno %></td>
				</tr>
				<tr>
					<td><b>Apellido materno</b><br/><small>Apellido materno del empleado</small></td>
					<td><%= @empleado.apellido_materno %></td>
				</tr>
				<tr>
					<td><b>RFC</b><br/><small>Registro Federal de Contribuyentes 
del empleado</small></td>
					<td><%= @empleado.rfc %></td>
				</tr>
				<tr>
					<td><b>Fecha de Nacimiento</b><br/><small>Fecha de nacimiento del empleado</small></td>
					<td><%= @empleado.fecha_nacimiento %></td>
				</tr>
				<tr>
					<td><b>Fecha de registro</b><br/><small>Fecha de registro del empleado al sistema</small></td>
					<td><%= @empleado.fecha_registro %></td>
				</tr>
				<tr>
					<td><b>Dirección</b><br/><small>Ubicación fiscal de la sucursal</small></td>
					<td><%= @empleado.direccion %></td>
				</tr>
				<tr>
					<td><b>Ciudad</b><br/><small>Municipio donde se ubica</small></td>
					<td><%= @empleado.ciudad %></td>
				</tr>
				<tr>
					<td><b>Estado</b><br/><small>Entidad federativa	</small></td>
					<td><%= @empleado.estado %></td>
				</tr>
				<tr>
					<td><b>Código postal </b></td>
					<td><%= @empleado.codigo_postal %></td>
				</tr>
			</table>
		</div>
		<div class="col-md-5">
			<h5 class="text-center">Datos del Usuario</h5>
			</br>
			<% if @empleado.usuarios.any? %> 
			  <% @empleado.usuarios.each do |usuario| %> 
			  	<table class="table table-sm table_show">
			  		<tr>
			  			<td><b>Nombre de usuario</b></br><small>Nombre único que identifica al usuario</small></td>
			  			<td><%= usuario.usuario %></td>
			  		</tr>
			  		<tr>
			  			<td><b>Email</b></br><small>Dirección de correo electrónico</small></td>
			  			<td><%= usuario.email %></td>
			  		</tr>
			  		<tr>
			  			<td><b>Rol</b></br><small>Nivel de privilegios del usuario</small></td>
			  			<td><%= usuario.tipo %></td>
			  		</tr>
			  	</table>
			  <% end %> 
			<% end %>
		</div>
	</div>
	<br>
	<table class="table_show">
		<tr>
			<td><%= link_to 'Modificar', edit_empleado_path(@empleado), class: 'btn btn-sm btn-primary' %>  </td>
			<td><%= link_to 'Nuevo', new_empleado_path, class: 'btn btn-sm btn-primary' %>  </td>
			<td><%= link_to 'Regresar', empleados_path, class: 'btn btn-sm btn-primary' %></td>
		</tr>
	</table>
	<!--end-->