config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  post 'productos/formulario_kit', as: 'formulario_kit'
  post 'productos/agregar_producto_kit', as: 'agregar_producto_kit'
  get 'welcome/index'
  resources :categorias
  resources :productos
  resources :unidades
  resources :configuraciones
  resources :empresas
  resources :cambio_sucursal
  resources :proveedores
  resources :clientes
  resources :tipos_pagos
  resources :inventarios
  resources :sucursales
  resources :terminales
  resources :cajas_registradoras
  resources :descuentos
  resources :cambio_sucursal do
    post :cambiar, :on => :collection
  end
  resources :empleados
  get 'permisos/mod_usuarios'
  get 'permisos/show_modulos'
  get 'permisos/mod_usuarios_rest'
  post 'terminales/actualiza'
  post 'terminales/caja_registradora'
  post 'permisos/guardar_cambios'
  post 'empleados/actualiza'
  post 'descuentos/opciones'
  post 'descuentos/agregar_producto'
  post 'descuentos/agregar_productos'
  post 'descuentos/obtener_categoria'
  post 'descuentos/total_producto'

  root 'welcome#index'

end

app/models/cajas_registradora.rb
class CajasRegistradora < ActiveRecord::Base
  has_many :terminales
end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  has_and_belongs_to_many :productos
  has_many :descuentos
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/models/descuento.rb
class Descuento < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :terminal
  belongs_to :categoria
  has_many :descuentos_productos
  has_many :descuentos_productos, dependent: :destroy
  has_many :productos, through: :descuentos_productos
end

app/models/descuentos_producto.rb
class DescuentosProducto < ActiveRecord::Base
  belongs_to :descuento
  belongs_to :producto
end

app/models/empleado.rb
class Empleado < ActiveRecord::Base
	has_many :usuarios, dependent: :destroy
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base

   has_attached_file :imagen, styles: { medium: "200x200>", thumb: "200x200>" }, default_url: "/images/:style/missing.png", validate_media_type: false

validates_attachment_content_type :imagen, content_type: /\Aimage\/.*\Z/

end

app/models/inventario.rb
class Inventario < ActiveRecord::Base
  has_many :terminales
end

app/models/kit.rb
class Kit < ActiveRecord::Base
end

app/models/modulo.rb
class Modulo < ActiveRecord::Base
	has_many :usuarios, through: :modulos_usuarios
end

app/models/modulos_usuario.rb
class ModulosUsuario < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :modulo
end

app/models/producto.rb
class Producto < ActiveRecord::Base
  belongs_to :unidad
  has_and_belongs_to_many :categorias
  has_many :descuentos_productos
  has_many :descuentos, through: :descuentos_productos
  has_attached_file :imagen, styles: { medium: "200x200>", thumb: "200x200>" }, default_url: "/images/:style/missing.png", validate_media_type: false
  validates_attachment_content_type :imagen, content_type: /\Aimage\/.*\Z/
end

app/models/proveedor.rb
class Proveedor < ActiveRecord::Base
end

app/models/rol.rb
class Rol < ActiveRecord::Base
	belongs_to :usuario
end

app/models/sucursal.rb
class Sucursal < ActiveRecord::Base
  has_many :terminales
end

app/models/terminal.rb
class Terminal < ActiveRecord::Base
  belongs_to :sucursal
  belongs_to :cajas_registradora
  belongs_to :inventario

  #validates :nombre, uniqueness: { case_sensitive: false }
end

app/models/tipos_pago.rb
class TiposPago < ActiveRecord::Base
end

app/models/unidad.rb
class Unidad < ActiveRecord::Base
  belongs_to  :producto
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  #devise :database_authenticatable, :registerable,
   #      :recoverable, :rememberable, :validatable
  belongs_to :empleado
  belongs_to :rol
  has_many :modulos_usuarios, dependent: :destroy
  has_many :modulos, through: :modulos_usuarios
  
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :definirControlador,:quitarBandera

  def formulario_kit
    @productos = Categoria.find(params[:cat_id].to_i).productos.where("kit = false")
    respond_to do |format|
      format.js
    end
  end
  def agregar_producto_kit
    @producto_kit = Producto.find(params[:pro_id].to_i)
    respond_to do |format|
      format.js
    end
  end
  def index
    @productos = Producto.all
    @categorias = Categoria.all
    @unidades = Unidad.all.sort
  end
  def new
    @productos = Categoria.first.productos.where("kit = false")
    @producto = Producto.new
    @categorias = Categoria.all
    @unidades = Unidad.all.sort
    @categorias_enlazadas = Array.new
    @creacion = true
  end
  def create
    #flash[:success] = params[:productos_kit]
    @producto = Producto.new(paramsDeProducto)
    if @producto.save
      agregarCategorias unless params[:categoria].nil?  #solo entra en la función si no es nil el parametro
      flash[:success] = "Producto creado exitosamente"
      agregarProductoskit if @producto.kit
      redirect_to @producto
    else
      flash[:error] ="Error al crear el producto"
    end

  end
  def show
    @producto = Producto.find(params[:id])
    @unidad=Unidad.find(@producto.unidad_id)
    @productos_del_kit = Kit.where("producto_padre_id = ?",@producto.id.to_i) if @producto.kit
  end
  def edit
    @productos = Categoria.first.productos
    @producto = Producto.find(params[:id])
    @categorias = Categoria.all
    @unidades = Unidad.all.sort
    @categorias_enlazadas = @producto.categorias #variable para indicar que categorías están enlazadas
    @productos_del_kit = Kit.where("producto_padre_id = ?",@producto.id.to_i) if @producto.kit
  end
  def update
    @producto = Producto.find(params[:id])
    if @producto.update(paramsDeProducto)
      @producto.categorias.clear # se borra de la base de datos antes de volver a agregar
      agregarCategorias unless params[:categoria].nil? #solo entra en la función si no es nil el parametro
      Kit.where("producto_padre_id = ?",@producto.id.to_i).delete_all
      agregarProductoskit if @producto.kit
      flash[:success] = "Producto actualizado exitosamente"
      redirect_to @producto
    else
      flash[:error] = "Error al actualizar el producto"
      render 'edit'
    end
  end
  def destroy
    @producto = Producto.find(params[:id].to_i)
    if @producto.kit
      Kit.where("producto_padre_id = ?",@producto.id).delete_all
    end
    if @producto.destroy
      flash[:success] = "Producto eliminado exitosamente"
      redirect_to @producto
    else
      flash[:error] = "Error al eliminar el producto"
    end

  end
  def checkKit
    respond_to do |format|
      format.js
    end
  end
  private
    def paramsDeProducto
      params.require(:producto).permit(:nombre,:definicion,:codigo,:lugar,:kit,:disponible_en_inventario,:unidad_id,:precio,:precio_costo,:iva,:imagen)
    end
    def agregarCategorias #funcion de agregar categorias
      params[:categoria].each do |c|
        categoria_enlazar = Categoria.find(c)
        @producto.categorias << categoria_enlazar
      end
    end
    def definirControlador
      @controlador = 'productos'
      @controladorSingular = 'el producto'
    end
    def quitarBandera
      @creacion = false
    end
    def agregarProductoskit
        kit_productos = params[:productos_kit].split(",")
        kit_cantidades = params[:cantidades_kit].split(",")
        i=0
        kit_productos.each do |p|
          kit = Kit.new
          kit.producto_padre_id=@producto.id
          kit.producto_id = p.to_i
          kit.cantidad = kit_cantidades[i].to_i
          kit.save
          i=i+1
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :usuario
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:usuario]
  end

end

app/views/productos/_form.html.erb
<%= form_for @producto do |f| %>
  <div class="col-md-12 align-content-center">
    <table class="table table-hover">
      <tr class="field">
        <td>
          <%=f.label 'Nombre*' %>
          <br><small> Nombre que identifica el producto</small>
        </td>
        <td>
          <%=f.text_field :nombre,id: 'nombre',placeholder:'Ingrese el nombre del producto' ,class: 'form-control' %>
          <small id="msg_nombre"></small>
        </td>
      </tr>
      <tr class="field">
        <td>
          <%=f.label 'Descripción*' %>
          <br><small> Descripción del producto</small>
        </td>
        <td>
          <%=f.text_field :definicion ,id: 'descripcion',placeholder:'Ingrese la descripción del producto',class: 'form-control' %>
          <small id="msg_descripcion"></small>
        </td>
      </tr>
      <tr class="field">
        <td>
          <%=f.label 'Código*' %>
          <br><small> Nombre clave único para identificar un producto</small>
        </td>
        <td>
          <%=f.text_field :codigo,id: 'codigo',placeholder:'Ingrese el código del producto' ,class: 'form-control' %>
          <small id="msg_codigo"></small>
        </td>
      </tr>
      <tr class="field">
        <td>
          <%=f.label 'Localización' %>
          <br><small> Nombre que identifica la localización física del producto</small>
        </td>
        <td>
          <%=f.text_field :lugar,placeholder:'Ingrese el lugar del producto' ,class: 'form-control' %>
        </td>
      </tr>
      <tr class="field">
        <td>

          <div class="form-check">
            <label class="form-check-label">
              <%=f.check_box :kit, class: 'form-check-input',id: 'check_kit'%>

                <%=f.label :kit, class: 'form-check-label'%>

            </label><br>
            <small>Campo que identifica si el producto contiene otros productos</small>
          </div>

        </td>
        <td >

        </td>
      </tr>
      <tr id="form_kit" <% if !@producto.kit %>style="display: none"<% end %> >
        <td>
          <label>Categoría</label>
          <%= select_tag :cat_id,options_for_select(@categorias.collect{ |categoria| [categoria.nombre, categoria.id]}),id: 'cat_select',class: 'custom-select', value:formulario_kit_path  %>
          <div id="div_pro_select">
            <br>
            <label>Producto</label>
            <%= select_tag :pro_id,options_for_select(@productos.collect{ |producto| [producto.nombre, producto.id]}),id: 'pro_select', class: 'custom-select' %>
          </div>
          <br>
          <a id="btnAgregar" class="btn btn-primary text-light btn-sm" value="<%= agregar_producto_kit_path %>">
            Agregar
          </a>
        </td>
        <td>
          <label>Productos dentro del Kit</label>
          <table class="table table-sm table-bordered">
            <thead class="bg-primary text-light">
            <th class="col-9">Nombre</th>
            <th class="col-2">Cantidad</th>
            <th class="col-1 eliminar">Quitar</th>
            </thead>
            <tbody id="tbody_kit">
              <%@productos_del_kit.each do |pro_kit|  %>
              <tr id="<%= pro_kit.producto_id%>" class="fila_kit" >
                <td >
                  <%= Producto.find(pro_kit.producto_id.to_i).nombre %>
                </td>
                <td>
                  <%= number_field_tag 'quantity', pro_kit.cantidad.to_s, within: 1...100, maxlength: 2 %>
                </td>
                <td class="text-center">
                  <%= (fa_icon 'trash', class: "eliminar btn btn-danger")  %>
                </td>
              </tr>
              <% end if @producto.kit%>
            </tbody>
          </table>
          <small id="mensaje_kit"></small>
        </td>
      </tr>
      <tr class="field">
        <td width="50%">
          <div class="form-check">
            <label class="form-check-label">
              <%=f.check_box :disponible_en_inventario, class: 'form-check-input'%><%=f.label :disponible_en_inventario, class: 'form-check-label'%>
            </label><br>
            <small>Campo que identifica si el producto está físicamente en el inventario</small>
          </div>
        </td>
        <td width="50%">
          <div class="form-check">
            <label class="form-check-label">
              <%=f.check_box :iva, class: 'form-check-input'%><%=f.label 'IVA', class: 'form-check-label'%>
            </label>
            <br><small>Campo que identifica si al producto se le agrega el IVA</small>
          </div>
        </td>
      </tr>
      <tr class="field">
        <td>
          <%=f.label 'Precio*'%><br>
          <small>Precio al que se venderá el producto</small>
        </td>
        <td>
          <div class="input-group mb-2">
            <div class="input-group-prepend">
              <span class="input-group-text">$</span>
            </div>
            <%=f.text_field :precio,id:'precio', class: 'form-control',placeholder: 'Ingrese el precio de venta'%>

          </div>
          <small id="msg_precio"></small>
        </td>
      </tr>
      <tr class="field">
        <td>
          <%=f.label 'Costo*'%><br>
          <small> Precio al que se compró el producto</small>
        </td>
        <td>
          <div class="input-group mb-2">
            <div class="input-group-prepend">
              <span class="input-group-text">$</span>
            </div>
            <%=f.text_field :precio_costo, id: 'precio_costo' ,class: 'form-control',placeholder: 'Ingrese el precio de compra'%>
          </div>
          <small id="msg_precio_costo"></small>

        </td>
      </tr>
      <tr class="field">
        <td>
          <label>Categorías</label><br>
          <small>Categorías a las que pertenece el producto</small>
        </td>
        <td id="lista_categorias">
          <% @categorias.each do |categoria| %>
          <div class="form-check">
            <label class="form-check-label">
              <%if @categorias_enlazadas.include?(categoria)%>
                <%= check_box_tag "categoria[]", categoria.id,checked= true, class: 'form-check-input'%><%=f.label categoria.nombre, class: 'form-check-label'  %>
              <%else%>
                <%=check_box_tag "categoria[]",categoria.id,checked=false,{class: 'form-check-input',checked: false}%><%=f.label categoria.nombre , class: 'form-check-label' %>
              <%end %>
            </label>
          </div>
          <% end %>
          <small id="mensaje_categorias"></small>
        </td>
      </tr>
      <tr class="field">
        <td>
          <label>Unidades</label><br>
          <small>Unidades de medición en las que se vende el producto</small>
        </td>
        <td>

          <%=f.select(:unidad_id,{},{},{class: 'custom-select'}) do %>

            <% @unidades.each do |unidad| %>
              <% if unidad.id != @producto.unidad_id%>
                <%= content_tag :option, unidad.nombre ,value: unidad.id %>
              <% else %>
                <%= content_tag :option, unidad.nombre ,value: unidad.id,selected: 'selected'%>
              <% end %>
            <% end %>
          <%  end  %>
        </td>
      </tr>
      <tr class="field" >
        <td>
          <label>Logotipo:</label><br>
          <small>Imagen del producto</small>
        </td>
        <td>
          <%= f.file_field :imagen, class: 'filestyle'%>
        </td>
      </tr>
      <tr>
      </tr>
    </table>
    <table class="table table-responsive-sm">
      <tr>
        <!--botón nombre, cambia respecto a la función que hace-->
        <td align="center"><br><small class="form-text text-muted">Nota: Los campos marcados con * son obligatorios</small>
          <br>
          <%= hidden_field_tag :productos_kit,"",{id: "array_productos"}%>
          <%= hidden_field_tag :cantidades_kit,"",{id: "array_cantidades"}%>
          <!-- funcion cancelar-->
          <% if nombre=="Crear Producto" %>
            <%=f.submit 'Guardar',id: 'btnGuardar', class:'btn btn-primary btn-sm', onclick: 'return validarFormularioProductos();' %>
          <% else %>
            <%= f.submit 'Guardar Cambios',id: 'btnGuardar', class:'btn btn-primary btn-sm', onclick: 'return validarFormularioProductos();'%>
          <% end %>

          <%= link_to 'Cancelar', '#',id:"cancelar",class:'btn btn-danger btn-sm',data: {toggle: 'modal', target: '#ModalForm'} %>
        </td>
      </tr>
    </table>
  </div>
<% end %>

app/views/productos/_producto_select.html.erb
<br>
<label>Producto</label>
<%= select_tag :pro_id,options_for_select(@productos.collect{ |producto| [producto.nombre, producto.id]}),id: 'pro_select',class: 'custom-select' %>

app/views/productos/_tbody_kit.html.erb
  <tr id="<%= @producto_kit.id%>" class="fila_kit" >
    <td >
      <%= @producto_kit.nombre %>
    </td>
    <td>
      <%= number_field_tag 'quantity', '1', within: 1...100 %>
    </td>
    <td class="text-center">
      <%= (fa_icon 'trash', class: "eliminar btn btn-danger")  %>
    </td>
  </tr>

app/views/productos/agregar_producto_kit.js.erb
if ($("#<%=@producto_kit.id%>").length== 0)
$('#tbody_kit').append("<%= j (render 'tbody_kit') %>")
else
{
	var band = parseInt($("#<%=@producto_kit.id%>").children().children("input").val()) + 1;
    if(band!== 100)
    $("#<%=@producto_kit.id%>").children().children("input").val(band);
}

$(".eliminar").click(function () {
    $(this).parents(".fila_kit").remove();
})

app/views/productos/edit.html.erb
<h3 class="text-center">Modificación del Producto</h3>
<%= render 'form', nombre: 'Editar Producto'%>

app/views/productos/formulario_kit.js.erb
$('#div_pro_select').html("<%= j (render 'producto_select') %>");

app/views/productos/index.html.erb
<div class="panel panel-info">
  <div class="panel-heading"><h4 class="text-center">Catálogo de Productos</h4></div>
  <div class="panel-body">
    <br>
    <%if @categorias.size >0 %>
      <%if @unidades.size > 0 %>
        <% if @productos.size > 0 %>
        <table class="table table-sm table-bordered">
          <thead class="bg-primary text-light">
          <th>Nombre</th>
          <th>Categorías</th>
          <th>Precio</th>
          <th>Precio Costo</th>
          <th>IVA</th>
          <th colspan="3">Opciones</th>
          </thead>
          <tbody>
          <% @productos.each do |producto| %>
            <tr>
              <td><%= producto.nombre %></td>
              <td>
                <%i=0 %>
                <% producto.categorias.each do |c| #función para tener la sintaxis correcta  %>
                  <% unless (i+1)==producto.categorias.length  %>
                    <%=c.nombre + ","%>
                  <% else %>
                    <%=c.nombre + "."%>
                  <%end%>
                  <%i=i+1 %>
                <%end%></td>
              <td><%= number_to_currency(producto.precio) %></td>
              <td><%= number_to_currency(producto.precio_costo) %></td>
              <td class="text-center"><%= check_box_tag 'IVA','IVA',checked = producto.iva,{:disabled =>'true'} %></td>
              <td class="text-center"><%= link_to (fa_icon 'eye'), producto_path(producto),title: 'Mostrar' %></td>
              <td class="text-center"><%= link_to (fa_icon 'edit'), edit_producto_path(producto),title: 'Editar' %></td>
              <td class="text-center">
                <%= link_to (fa_icon 'trash'), '#', data: { toggle: 'modal', target: '#ModalIndex' } ,
                            onclick:('cambiarIdYNombre('+producto.id.to_s+',"'+@controlador.to_s+'","'+ @controladorSingular.to_s+'","'+ producto.nombre+'");return false;'),
                            title: 'Eliminar' %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
          <table class="table text-center" >
            <tr>
              <td><%= link_to 'Nuevo', new_producto_path, class: 'btn btn-primary btn-sm' %></td>
            </tr>
          </table>

          <% else %>
          <br>
          <h5 align="center"><%= "No existen productos actualmente" %> </h5>
          <table class="table text-center" >
            <tr>
              <td><%= link_to 'Nuevo', new_producto_path, class: 'btn btn-primary btn-sm' %></td>
            </tr>
          </table>
          <% end %>
      <% else %>
        <br>
        <h5 align="center"><%= "No existen unidades actualmente, necesitas al menos una unidad" %> </h5>
        <table class="table text-center" >
          <tr>
            <td><%= link_to 'Nueva unidad', new_unidad_path, class: 'btn btn-primary btn-sm' %></td>
          </tr>
        </table>
      <%end%>
    <%else %>
      <br>
      <h5 align="center"><%= "No existen categorías actualmente, necesitas al menos una categoría" %> </h5>
      <table class="table text-center" >
        <tr>
          <td><%= link_to 'Nueva categoría', new_categoria_path, class: 'btn btn-primary btn-sm' %></td>
        </tr>
      </table>
    <%end %>
  </div>
</div>

app/views/productos/new.html.erb
<h4 class="text-center">Nuevo Producto</h4>
<%= render 'form', nombre: 'Crear Producto' %>

app/views/productos/show.html.erb
<div class="col-md-12 align-content-center">
<h4 class="text-center">Vista de un producto</h4>
      </br>
      <div class="row">
        </br>
        <table class="table">
          <tr>
            <td width="50">
              <b>Nombre</b><br>
              <small> Nombre que identifica el producto</small>
            </td>
            <td><%= @producto.nombre %><br>

            </td>
          </tr>
          <tr>
            <td width="50"><b>Descripción</b><br>
              <small> Descripción del producto</small>
            </td>
            <td>
              <%= @producto.definicion%>
            </td>
          </tr>
          <tr>
            <td width="50">
              <b>Código</b>
              <br><small> Nombre clave único para identificar un producto</small>
            </td>
            <td><%= @producto.codigo%></td>
          </tr>
          <tr>
            <td width="40%"><b>Localización.</b><br>
              <small> Nombre que identifica la localización física del producto</small>
            </td>
            <td><%= @producto.lugar %></td>
          </tr>
          <% if @producto.kit %>
          <tr>
            <td width="20">
              <b>Kit</b><br>
              <small>Productos que están dentro del kit</small>
            </td>
            <td>
              <table class="table table-sm table-bordered">
                <thead class="bg-primary text-light">
                <th class="col-9">Nombre</th>
                <th class="col-3">Cantidad</th>
                </thead>
                <tbody>
                <% @productos_del_kit.each do |p|%>
                  <tr>
                    <td>
                      <%= Producto.find(p.producto_id.to_i).nombre %>
                    </td>
                    <td>
                      <%= p.cantidad  %>
                    </td>
                  </tr>
                <% end %>
                </tbody>
              </table>


            </td>
          </tr>
            <% end %>
          <tr>
            <td width="20">
              <b>Disponible en inventario</b>
              <br>
              <small>Campo que identifica si el producto está físicamente en el inventario</small>
            </td>
            <td><%= check_box_tag 'disponible_en_inventario','disponible_en_inventario',checked = @producto.disponible_en_inventario,{:disabled =>'true'}%></td>
          </tr>
          <tr>
            <td width="20">
              <b>IVA</b>
              <br><small>Campo que identifica si al producto se le agrega el IVA</small>
            </td>
            <td><%= check_box_tag 'IVA','IVA',checked = @producto.iva,{:disabled =>'true'} %></td>
          </tr>
          <tr>
            <td width="20">
              <b>Precio</b>
              <br>
              <small>Precio al que se venderá el producto</small>
            </td>
            <td><%= number_to_currency(@producto.precio) %></td>
          </tr>
          <tr>
            <td width="20">
              <b>Costo </b>
              <br>
              <small> Precio al que se compró el producto</small>
            </td>
            <td><%= number_to_currency(@producto.precio_costo) %></td>
          </tr>
          <tr>
            <td width="20"><b>Categorías </b>
              <br>
              <small>Categorías a las que pertenece el producto</small>
            </td>
            <td>
              <% @producto.categorias.each do |c| %>
                <%=c.nombre %><br>
              <%end%>
            </td>
          </tr>
          <tr>
            <td width="20"><b>Unidades</b><br>
              <small>Unidades de medición en las que se vende el producto</small>
            </td>
            <td><%= @unidad.nombre %></td>
          </tr>
          <tr>
            <td>
              <label> Logotipo </label>
              <br>
              <small>Imagen del producto</small>
            </td>
            <td><%= image_tag @producto.imagen.url(:medium) %></td>
          </tr>
        </table>
      </div>
      <br>
      <div class="text-center">
        <table class="table table-responsive-sm">
          <tr>
            <td><%= link_to 'Modificar', edit_producto_path(@producto),class: 'btn btn-primary  btn-sm' %>
              <%= link_to 'Nuevo', new_producto_path, class: 'btn btn-primary btn-sm' %>
              <%= link_to 'Regresar', productos_path,class: 'btn btn-primary btn-sm' %>
            </td>
          </tr>
        </table>
      </div>
      <!--end-->
</div>